import { C } from '../utils/ColorPalette';

const _ = C.TRANSPARENT;

// Click indicator ring (8×8) — shown when player clicks the world
export const CLICK_RING: number[][] = [
  [_,_,C.YELLOW,C.YELLOW,C.YELLOW,C.YELLOW,_,_],
  [_,C.YELLOW,_,_,_,_,C.YELLOW,_],
  [C.YELLOW,_,_,_,_,_,_,C.YELLOW],
  [C.YELLOW,_,_,_,_,_,_,C.YELLOW],
  [C.YELLOW,_,_,_,_,_,_,C.YELLOW],
  [C.YELLOW,_,_,_,_,_,_,C.YELLOW],
  [_,C.YELLOW,_,_,_,_,C.YELLOW,_],
  [_,_,C.YELLOW,C.YELLOW,C.YELLOW,C.YELLOW,_,_],
];

// Inventory slot background (18×18)
export const SLOT_BG: number[][] = Array.from({ length: 18 }, (_, r) =>
  Array.from({ length: 18 }, (_, c) => {
    if (r === 0 || c === 0) return C.DARKER_GREY;
    if (r === 17 || c === 17) return C.LIGHT_GREY;
    return C.DARK_GREY;
  }),
);

// Inventory slot hover (18×18)
export const SLOT_HOVER: number[][] = Array.from({ length: 18 }, (_, r) =>
  Array.from({ length: 18 }, (_, c) => {
    if (r === 0 || c === 0) return C.MID_GREY;
    if (r === 17 || c === 17) return C.WHITE;
    return C.MID_GREY;
  }),
);

// Coin icon (10×10)
export const COIN_ICON: number[][] = [
  [_,_,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,_,_],
  [_,C.DARK_BROWN,C.GOLD,C.GOLD,C.GOLD,C.GOLD,C.GOLD,C.GOLD,C.DARK_BROWN,_],
  [C.DARK_BROWN,C.GOLD,C.YELLOW,C.YELLOW,C.YELLOW,C.YELLOW,C.YELLOW,C.GOLD,C.GOLD,C.DARK_BROWN],
  [C.DARK_BROWN,C.GOLD,C.YELLOW,C.GOLD,C.GOLD,C.GOLD,C.YELLOW,C.YELLOW,C.GOLD,C.DARK_BROWN],
  [C.DARK_BROWN,C.GOLD,C.YELLOW,C.GOLD,C.GOLD,C.GOLD,C.GOLD,C.YELLOW,C.GOLD,C.DARK_BROWN],
  [C.DARK_BROWN,C.GOLD,C.YELLOW,C.GOLD,C.GOLD,C.GOLD,C.GOLD,C.YELLOW,C.GOLD,C.DARK_BROWN],
  [C.DARK_BROWN,C.GOLD,C.YELLOW,C.GOLD,C.GOLD,C.GOLD,C.YELLOW,C.YELLOW,C.GOLD,C.DARK_BROWN],
  [C.DARK_BROWN,C.GOLD,C.YELLOW,C.YELLOW,C.YELLOW,C.YELLOW,C.YELLOW,C.GOLD,C.GOLD,C.DARK_BROWN],
  [_,C.DARK_BROWN,C.GOLD,C.GOLD,C.GOLD,C.GOLD,C.GOLD,C.GOLD,C.DARK_BROWN,_],
  [_,_,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,_,_],
];

// Heart (for pet happiness) (8×8)
export const HEART: number[][] = [
  [_,C.RED,C.RED,_,_,C.RED,C.RED,_],
  [C.RED,C.PINK,C.RED,C.RED,C.RED,C.RED,C.PINK,C.RED],
  [C.RED,C.PINK,C.PINK,C.PINK,C.PINK,C.PINK,C.RED,C.RED],
  [C.RED,C.RED,C.PINK,C.PINK,C.PINK,C.RED,C.RED,_],
  [_,C.RED,C.RED,C.PINK,C.RED,C.RED,_,_],
  [_,_,C.RED,C.RED,C.RED,_,_,_],
  [_,_,_,C.RED,_,_,_,_],
  [_,_,_,_,_,_,_,_],
];

// Sleep Z icon (6×6)
export const SLEEP_Z: number[][] = [
  [_,C.PALE_BLUE,C.PALE_BLUE,C.PALE_BLUE,C.PALE_BLUE,_],
  [_,_,_,_,C.PALE_BLUE,_],
  [_,_,_,C.PALE_BLUE,_,_],
  [_,_,C.PALE_BLUE,_,_,_],
  [_,C.PALE_BLUE,_,_,_,_],
  [_,C.PALE_BLUE,C.PALE_BLUE,C.PALE_BLUE,C.PALE_BLUE,_],
];

// Simple bed sprite (16×12) — for farmhouse interior
export const BED: number[][] = [
  [C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN],
  [C.DARK_BROWN,C.WHITE,C.WHITE,C.WHITE,C.LIGHT_BLUE,C.LIGHT_BLUE,C.LIGHT_BLUE,C.LIGHT_BLUE,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.DARK_BROWN],
  [C.DARK_BROWN,C.WHITE,C.WHITE,C.WHITE,C.LIGHT_BLUE,C.LIGHT_BLUE,C.LIGHT_BLUE,C.LIGHT_BLUE,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.DARK_BROWN],
  [C.DARK_BROWN,C.WHITE,C.WHITE,C.WHITE,C.LIGHT_BLUE,C.LIGHT_BLUE,C.LIGHT_BLUE,C.LIGHT_BLUE,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.DARK_BROWN],
  [C.DARK_BROWN,C.WHITE,C.WHITE,C.WHITE,C.LIGHT_BLUE,C.LIGHT_BLUE,C.LIGHT_BLUE,C.LIGHT_BLUE,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.DARK_BROWN],
  [C.DARK_BROWN,C.WHITE,C.WHITE,C.WHITE,C.LIGHT_BLUE,C.LIGHT_BLUE,C.LIGHT_BLUE,C.LIGHT_BLUE,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.DARK_BROWN],
  [C.DARK_BROWN,C.WHITE,C.WHITE,C.WHITE,C.LIGHT_BLUE,C.LIGHT_BLUE,C.LIGHT_BLUE,C.LIGHT_BLUE,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.DARK_BROWN],
  [C.DARK_BROWN,C.WHITE,C.WHITE,C.WHITE,C.LIGHT_BLUE,C.LIGHT_BLUE,C.LIGHT_BLUE,C.LIGHT_BLUE,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.DARK_BROWN],
  [C.DARK_BROWN,C.WHITE,C.WHITE,C.WHITE,C.LIGHT_BLUE,C.LIGHT_BLUE,C.LIGHT_BLUE,C.LIGHT_BLUE,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.DARK_BROWN],
  [C.DARK_BROWN,C.WHITE,C.WHITE,C.WHITE,C.WHITE,C.WHITE,C.WHITE,C.WHITE,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.DARK_BROWN],
  [C.DARK_BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.DARK_BROWN],
  [C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN],
];

// Farmhouse exterior (16×16)
export const FARMHOUSE: number[][] = [
  [_,_,_,_,C.DARK_RED,C.DARK_RED,C.DARK_RED,C.DARK_RED,C.DARK_RED,C.DARK_RED,C.DARK_RED,C.DARK_RED,_,_,_,_],
  [_,_,_,C.DARK_RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.DARK_RED,_,_,_],
  [_,_,C.DARK_RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.DARK_RED,_,_],
  [_,C.DARK_RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.DARK_RED,_],
  [C.DARK_RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.RED,C.DARK_RED],
  [C.BROWN,C.LIGHT_BROWN,C.LIGHT_BROWN,C.LIGHT_BROWN,C.LIGHT_BROWN,C.LIGHT_BROWN,C.LIGHT_BROWN,C.LIGHT_BROWN,C.LIGHT_BROWN,C.LIGHT_BROWN,C.LIGHT_BROWN,C.LIGHT_BROWN,C.LIGHT_BROWN,C.LIGHT_BROWN,C.LIGHT_BROWN,C.BROWN],
  [C.BROWN,C.TAN,C.TAN,C.TAN,C.PALE_BLUE,C.PALE_BLUE,C.PALE_BLUE,C.TAN,C.TAN,C.PALE_BLUE,C.PALE_BLUE,C.PALE_BLUE,C.TAN,C.TAN,C.TAN,C.BROWN],
  [C.BROWN,C.TAN,C.TAN,C.TAN,C.PALE_BLUE,C.PALE_BLUE,C.PALE_BLUE,C.TAN,C.TAN,C.PALE_BLUE,C.PALE_BLUE,C.PALE_BLUE,C.TAN,C.TAN,C.TAN,C.BROWN],
  [C.BROWN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.BROWN],
  [C.BROWN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.BROWN],
  [C.BROWN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.BROWN],
  [C.BROWN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.BROWN,_,_,C.BROWN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.BROWN],
  [C.BROWN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.BROWN,_,_,C.BROWN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.BROWN],
  [C.BROWN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.BROWN,_,_,C.BROWN,C.TAN,C.TAN,C.TAN,C.TAN,C.TAN,C.BROWN],
  [C.DARK_BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.DARK_BROWN,_,_,C.DARK_BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.BROWN,C.DARK_BROWN],
  [C.ALMOST_BLACK,C.ALMOST_BLACK,C.ALMOST_BLACK,C.ALMOST_BLACK,C.ALMOST_BLACK,C.ALMOST_BLACK,C.ALMOST_BLACK,_,_,C.ALMOST_BLACK,C.ALMOST_BLACK,C.ALMOST_BLACK,C.ALMOST_BLACK,C.ALMOST_BLACK,C.ALMOST_BLACK,C.ALMOST_BLACK],
];

// Tree (16×24) — 2 tiles tall
export const TREE_TOP: number[][] = [
  [_,_,_,_,_,C.DARK_GREEN,C.DARK_GREEN,C.DARK_GREEN,C.DARK_GREEN,C.DARK_GREEN,C.DARK_GREEN,_,_,_,_,_],
  [_,_,_,C.DARK_GREEN,C.GREEN,C.GREEN,C.GREEN,C.PALE_GREEN,C.GREEN,C.GREEN,C.GREEN,C.DARK_GREEN,_,_,_,_],
  [_,_,C.DARK_GREEN,C.GREEN,C.GREEN,C.PALE_GREEN,C.GREEN,C.GREEN,C.PALE_GREEN,C.GREEN,C.PALE_GREEN,C.GREEN,C.DARK_GREEN,_,_,_],
  [_,C.DARK_GREEN,C.GREEN,C.GREEN,C.PALE_GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.PALE_GREEN,C.GREEN,C.GREEN,C.GREEN,C.DARK_GREEN,_,_],
  [_,C.DARK_GREEN,C.GREEN,C.PALE_GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.PALE_GREEN,C.GREEN,C.PALE_GREEN,C.DARK_GREEN,_,_],
  [C.DARK_GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.PALE_GREEN,C.GREEN,C.GREEN,C.PALE_GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.DARK_GREEN,_],
  [C.DARK_GREEN,C.GREEN,C.PALE_GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.PALE_GREEN,C.GREEN,C.GREEN,C.GREEN,C.DARK_GREEN,_],
  [C.DARK_GREEN,C.GREEN,C.GREEN,C.PALE_GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.PALE_GREEN,C.GREEN,C.GREEN,C.DARK_GREEN,_],
  [C.DARK_GREEN,C.GREEN,C.GREEN,C.GREEN,C.PALE_GREEN,C.GREEN,C.GREEN,C.PALE_GREEN,C.GREEN,C.GREEN,C.PALE_GREEN,C.GREEN,C.GREEN,C.GREEN,C.DARK_GREEN,_],
  [C.DARK_GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.DARK_GREEN,_],
  [_,C.DARK_GREEN,C.GREEN,C.GREEN,C.PALE_GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.PALE_GREEN,C.GREEN,C.GREEN,C.PALE_GREEN,C.DARK_GREEN,_,_],
  [_,C.DARK_GREEN,C.GREEN,C.GREEN,C.GREEN,C.PALE_GREEN,C.GREEN,C.GREEN,C.PALE_GREEN,C.GREEN,C.GREEN,C.GREEN,C.DARK_GREEN,_,_,_],
  [_,_,C.DARK_GREEN,C.GREEN,C.GREEN,C.GREEN,C.PALE_GREEN,C.GREEN,C.GREEN,C.PALE_GREEN,C.GREEN,C.DARK_GREEN,_,_,_,_],
  [_,_,_,C.DARK_GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.GREEN,C.DARK_GREEN,_,_,_,_,_],
  [_,_,_,_,C.DARK_GREEN,C.DARK_GREEN,C.GREEN,C.GREEN,C.DARK_GREEN,C.DARK_GREEN,_,_,_,_,_,_],
  [_,_,_,_,_,_,C.LIGHT_BROWN,C.LIGHT_BROWN,_,_,_,_,_,_,_,_],
];

export const TREE_TRUNK: number[][] = [
  [_,_,_,_,_,_,C.LIGHT_BROWN,C.LIGHT_BROWN,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,C.BROWN,C.LIGHT_BROWN,C.LIGHT_BROWN,C.BROWN,_,_,_,_,_,_,_],
  [_,_,_,_,_,C.BROWN,C.ORANGE,C.ORANGE,C.BROWN,_,_,_,_,_,_,_],
  [_,_,_,_,_,C.BROWN,C.ORANGE,C.ORANGE,C.BROWN,_,_,_,_,_,_,_],
  [_,_,_,_,_,C.BROWN,C.LIGHT_BROWN,C.LIGHT_BROWN,C.BROWN,_,_,_,_,_,_,_],
  [_,_,_,_,_,C.BROWN,C.LIGHT_BROWN,C.LIGHT_BROWN,C.BROWN,_,_,_,_,_,_,_],
  [_,_,_,_,C.DARK_BROWN,C.BROWN,C.LIGHT_BROWN,C.LIGHT_BROWN,C.BROWN,C.DARK_BROWN,_,_,_,_,_,_],
  [_,_,_,_,C.DARK_BROWN,C.BROWN,C.LIGHT_BROWN,C.LIGHT_BROWN,C.BROWN,C.DARK_BROWN,_,_,_,_,_,_],
  [_,_,_,_,_,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,_,_,_,_,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
];

// Fence post (8×16)
export const FENCE_POST: number[][] = [
  [_,_,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,_,_],
  [_,C.DARK_BROWN,C.LIGHT_BROWN,C.LIGHT_BROWN,C.LIGHT_BROWN,C.LIGHT_BROWN,C.DARK_BROWN,_],
  [_,C.DARK_BROWN,C.LIGHT_BROWN,C.TAN,C.TAN,C.LIGHT_BROWN,C.DARK_BROWN,_],
  [_,C.DARK_BROWN,C.LIGHT_BROWN,C.LIGHT_BROWN,C.LIGHT_BROWN,C.LIGHT_BROWN,C.DARK_BROWN,_],
  [_,_,C.DARK_BROWN,C.BROWN,C.BROWN,C.DARK_BROWN,_,_],
  [_,_,C.DARK_BROWN,C.BROWN,C.BROWN,C.DARK_BROWN,_,_],
  [_,_,C.DARK_BROWN,C.BROWN,C.BROWN,C.DARK_BROWN,_,_],
  [_,_,C.DARK_BROWN,C.BROWN,C.BROWN,C.DARK_BROWN,_,_],
  [_,_,C.DARK_BROWN,C.BROWN,C.BROWN,C.DARK_BROWN,_,_],
  [_,_,C.DARK_BROWN,C.BROWN,C.BROWN,C.DARK_BROWN,_,_],
  [_,_,C.DARK_BROWN,C.BROWN,C.BROWN,C.DARK_BROWN,_,_],
  [_,_,C.DARK_BROWN,C.BROWN,C.BROWN,C.DARK_BROWN,_,_],
  [_,_,C.DARK_BROWN,C.BROWN,C.BROWN,C.DARK_BROWN,_,_],
  [_,_,C.DARK_BROWN,C.BROWN,C.BROWN,C.DARK_BROWN,_,_],
  [_,_,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,C.DARK_BROWN,_,_],
  [_,_,_,_,_,_,_,_],
];
